version: '3.8'

services:
  generations:
    build: ..
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./volume:/usr/src/app/volume
    ports:
       - "5000:5000"
    env_file:
      - .env.dev